FROM docker.io/library/rust:1.95.0-alpine3.22@sha256:064dfc925d68d1a63f4fd2871bd7dc6e6ea56692989a487185855d62885d90aa

RUN apk add --no-cache \
    pkgconfig \
    openssl-dev \
    musl-dev

WORKDIR /app
RUN mkdir -p /app/results

COPY src /app/src
COPY Cargo.toml Cargo.lock /app/
COPY payload.json /app/payload.json
COPY scripts/run.sh /app/run.sh

RUN cargo build --release --bins --target-dir /app

RUN chmod +x /app/run.sh
ENTRYPOINT ["/app/run.sh"]
