FROM rust:1.95.0-alpine3.22

RUN apk add --no-cache \
    pkgconfig \
    openssl-dev \
    musl-dev

WORKDIR /app
RUN mkdir -p /app/results

COPY src /app/src
COPY Cargo.toml Cargo.lock /app/
COPY payload.json /app/payload.json
COPY scripts/run.sh /app/run.sh

RUN cargo build --bin server && \
    cp /app/target/debug/server /app/server && \
    cargo build --bin client && \
    cp /app/target/debug/client /app/client

RUN chmod +x /app/run.sh
ENTRYPOINT ["/app/run.sh"]
