FROM docker.io/library/fedora:43@sha256:781b7642e8bf256e9cf75d2aa58d86f5cc695fd2df113517614e181a5eee9138

RUN dnf -y update && \
    dnf -y install \
    gcc \
    openssl-devel \
    pkgconf-pkg-config \
    curl && \
    dnf clean all

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN rustup toolchain install 1.95.0 && \
    rustup default 1.95.0

WORKDIR /app
RUN mkdir -p /app/results

COPY src /app/src
COPY Cargo.toml Cargo.lock /app/
COPY payload.json /app/payload.json
COPY scripts/run.sh /app/run.sh

RUN cargo build --release --bins --target-dir /app

RUN chmod +x /app/run.sh
ENTRYPOINT ["/app/run.sh"]
