FROM docker.io/library/rust:1.95.0-slim-trixie@sha256:76aa902d6549f89bcf89564fd3448bd4d802120d97433ea4d4324c26c7dc6ee9

WORKDIR /app
RUN mkdir -p /app/results

COPY src /app/src
COPY Cargo.toml Cargo.lock /app/
COPY payload.json /app/payload.json
COPY scripts/run.sh /app/run.sh

RUN cargo build --release --bins --target-dir /app

RUN chmod +x /app/run.sh
ENTRYPOINT ["/app/run.sh"]
